namespace SchoolPortal.Web.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class statesandcapital : DbMigration
    {
        public override void Up()
        {
            Sql("SET IDENTITY_INSERT States ON");
           
           

            Sql("INSERT INTO States (Id, StateName) VALUES (2, 'IMO')");
            Sql("INSERT INTO States (Id, StateName) VALUES (4, 'ABIA')");
            Sql("INSERT INTO States (Id, StateName) VALUES (5, 'ADAMAWA')");
            Sql("INSERT INTO States (Id, StateName) VALUES (6, 'AKWA IBOM')");
            Sql("INSERT INTO States (Id, StateName) VALUES (8, 'ANAMBRA')");
            Sql("INSERT INTO States (Id, StateName) VALUES (9, 'BAUCHI')");
            Sql("INSERT INTO States (Id, StateName) VALUES (10, 'BAYELSA')");
            Sql("INSERT INTO States (Id, StateName) VALUES (11, 'BENUE')");
            Sql("INSERT INTO States (Id, StateName) VALUES (12, 'BORNU')");
            Sql("INSERT INTO States (Id, StateName) VALUES (13, 'CROSS RIVER')");
            Sql("INSERT INTO States (Id, StateName) VALUES (14, 'DELTA')");
            Sql("INSERT INTO States (Id, StateName) VALUES (15, 'EBONYI')");
            Sql("INSERT INTO States (Id, StateName) VALUES (16, 'EDO')");
            Sql("INSERT INTO States (Id, StateName) VALUES (17, 'EKITI')");
            Sql("INSERT INTO States (Id, StateName) VALUES (18, 'ENUGU')");
            Sql("INSERT INTO States (Id, StateName) VALUES (19, 'GOMBE')");
            Sql("INSERT INTO States (Id, StateName) VALUES (20, 'JIGAWA')");
            Sql("INSERT INTO States (Id, StateName) VALUES (21, 'KADUNA')");
            Sql("INSERT INTO States (Id, StateName) VALUES (22, 'KANO')");
            Sql("INSERT INTO States (Id, StateName) VALUES (23, 'KATSINA')");
            Sql("INSERT INTO States (Id, StateName) VALUES (24, 'KEBBI')");
            Sql("INSERT INTO States (Id, StateName) VALUES (25, 'KOGI')");
            Sql("INSERT INTO States (Id, StateName) VALUES (26, 'KWARA')");
            Sql("INSERT INTO States (Id, StateName) VALUES (27, 'LAGOS')");
            Sql("INSERT INTO States (Id, StateName) VALUES (28, 'NASARAWA')");
            Sql("INSERT INTO States (Id, StateName) VALUES (29, 'NIGER')");
            Sql("INSERT INTO States (Id, StateName) VALUES (30, 'OGU')");
            Sql("INSERT INTO States (Id, StateName) VALUES (31, 'ONDO')");
            Sql("INSERT INTO States (Id, StateName) VALUES (33, 'OYO')");
            Sql("INSERT INTO States (Id, StateName) VALUES (34, 'PLATEAU')");
            Sql("INSERT INTO States (Id, StateName) VALUES (35, 'RIVERS ')");
            Sql("INSERT INTO States (Id, StateName) VALUES (36, 'SOKOTO')");
            Sql("INSERT INTO States (Id, StateName) VALUES (37, 'TARABA')");
            Sql("INSERT INTO States (Id, StateName) VALUES (38, 'YOBE')");
            Sql("INSERT INTO States (Id, StateName) VALUES (39, 'ZAMFARA')");
            Sql("INSERT INTO States (Id, StateName) VALUES (40, 'FEDERAL CAPITAL TERRITORY')");
            Sql("SET IDENTITY_INSERT States OFF");

            Sql("SET IDENTITY_INSERT LocalGovs ON");

            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (3, 'OWERRI MUNICIPAL', 2)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (4, 'ORLU', 2)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (5, 'EHIME MBANO', 2)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (6, 'ABA NORTH', 4)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (7, 'ABA SOUTH', 4)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (8, 'AROCHUKWU', 4)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (9, 'BENDE', 4)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (10, 'IKWUANO', 4)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (11, 'ISIALA NGWA NORTH', 4)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (12, 'ISIALA NGWA SOUTH', 4)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (13, 'ISUIKWUATO', 4)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (14, 'OBINGWA', 4)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (15, 'OHAFIA', 4)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (16, 'OSISIOMA NGWA', 4)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (17, 'UGWUNAGBO', 4)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (18, 'UKWA EAST', 4)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (19, 'UKWA WEST', 4)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (20, 'UMUAHIA NORTH', 4)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (21, 'UMUAHIA SOUTH', 4)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (22, 'UMUNNEOCHI', 4)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (23, 'DEMSA', 5)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (24, 'FUFORE', 5)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (25, 'GANAYE', 5)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (26, 'GIRERI', 5)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (27, 'GOMBI', 5)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (28, 'GUYUK', 5)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (29, 'HONG', 5)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (30, 'JADA', 5)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (31, 'LAMURDE', 5)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (32, 'MADAGALI', 5)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (33, 'MAIHA', 5)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (34, 'MAYO-BELWA', 5)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (35, 'MICHIKA', 5)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (36, 'MUBI NORTH', 5)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (37, 'MUBI SOUTH', 5)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (38, 'NUMAN', 5)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (39, 'SHELLENG', 5)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (40, 'SONG', 5)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (41, 'TOUNGO', 5)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (42, 'YOLA NORTH', 5)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (43, 'YOLA SOUTH', 5)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (44, 'ABAK', 6)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (45, 'EASTERN OBOLO', 6)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (46, 'EKET', 6)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (47, 'ESIT EKET', 6)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (48, 'ESSIEN UDIM ', 6)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (49, 'ETIM EKPO', 6)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (50, 'ETINAM', 6)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (51, 'IBESIKPO ASUTAN', 6)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (52, 'IKA', 6)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (53, 'IKONO', 6)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (54, 'IKOT ABASI', 6)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (55, 'IKOT EKPENE ', 6)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (56, 'INI', 6)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (57, 'ITU', 6)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (58, 'MBO', 6)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (59, 'MKPAT ENIN', 6)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (60, 'NSIT ATAI', 6)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (61, 'NSIT IBOM', 6)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (62, 'NSIT UBIUM', 6)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (63, 'OBOT AKARA ', 6)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (64, 'OKOBO', 6)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (65, 'ONNA', 6)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (66, 'ORON ', 6)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (67, 'ORUK ANAM', 6)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (68, 'UDUNG UKO', 6)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (69, 'UKANAFUN', 6)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (70, 'URUAN', 6)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (71, 'URUE-OFFIONG-ORUKO', 6)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (72, 'UYO', 6)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (73, 'AGUATA ', 8)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (74, 'ANAMBRA EAST', 8)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (75, 'ANAMBRA WEST', 8)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (76, 'ANAOCHA ', 8)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (77, 'AWKA NORTH ', 8)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (78, 'AWKA SOUTH ', 8)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (79, 'AYAMELUM ', 8)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (80, 'DUNUKOFIA ', 8)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (81, 'EKWUSIGO', 8)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (82, 'IDEMILI NORTH ', 8)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (83, 'IDEMILI SOUTH', 8)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (84, 'IHIALA ', 8)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (85, 'NJIKOKA', 8)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (86, 'NNEWI NORTH', 8)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (87, 'NNEWI SOUTH', 8)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (88, 'OGBARU', 8)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (89, 'ONITSHA NORTH ', 8)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (90, 'ONITSHA SOUTH', 8)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (91, 'ORUMBA NORTH ', 8)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (92, 'ORUMBA SOUTH', 8)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (93, 'OYI', 8)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (94, 'ALKALERI', 9)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (95, 'BAUCHI', 9)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (96, 'BOGORO', 9)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (97, 'DAMBAN', 9)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (98, 'DARAZO', 9)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (99, 'DASS', 9)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (100, 'GANJUWA', 9)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (101, 'GIADE', 9)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (102, 'ITAS-GADAU', 9)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (103, 'JAMA''ARE', 9)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (104, 'KATAGUM', 9)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (105, 'KIRFI', 9)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (106, 'MISAU', 9)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (107, 'NINGI', 9)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (108, 'SHIRA', 9)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (109, 'TAFAWA-BALEWA', 9)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (110, 'TORO', 9)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (111, 'WARJI', 9)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (112, 'ZAKI', 9)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (113, 'BRASS', 10)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (114, 'EKEREMOR', 10)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (115, 'KOLOKUMA-OPOKUMA', 10)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (116, 'NEMBE', 10)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (117, 'OGBIA', 10)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (118, 'SAGBAMA', 10)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (119, 'SOUTHERN JAW', 10)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (120, 'YENEGOA', 10)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (121, 'ADO', 11)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (122, 'AGATU', 11)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (123, 'APA', 11)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (124, 'BUJUKU', 11)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (125, 'GBOKO', 11)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (126, 'GUMA', 11)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (127, 'GWER EAST', 11)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (128, 'GWER WEST', 11)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (129, 'KASTINA-ALA', 11)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (130, 'KONSHISHA ', 11)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (131, 'KWANDE', 11)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (132, 'LOGO', 11)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (133, 'MAKURDI', 11)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (134, 'OBI', 11)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (135, 'OGBADIBO', 11)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (136, 'OJU', 11)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (137, 'OKPOKWU', 11)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (138, 'OHIMINI', 11)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (139, 'OTUKPO', 11)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (140, 'TARKA', 11)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (141, 'UKUM', 11)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (142, 'USHONGO', 11)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (143, 'VANDEIKYA', 11)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (144, 'ADADAM', 12)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (145, 'ASKIRA-UBA', 12)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (147, 'BAMA', 12)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (148, 'BAYO', 12)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (149, 'BIU', 12)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (150, 'CHIBOK', 12)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (151, 'DAMBOA', 12)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (152, 'DIKWA', 12)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (153, 'GUBIO', 12)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (154, 'GUZAMALA', 12)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (155, 'GWOZA', 12)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (156, 'HAWUL', 12)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (157, 'JERE', 12)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (158, 'KAGA', 12)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (159, 'KALA-BALGE', 12)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (160, 'KONDUGA', 12)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (161, 'KUKAWA', 12)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (162, 'KWAYA KUSAR', 12)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (163, 'MAFA', 12)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (164, 'MAGUMERI', 12)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (165, 'MAIDUGURI', 12)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (166, 'MARTE', 12)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (167, 'MOBBAR', 12)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (168, 'MONGUNO', 12)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (169, 'NGALA', 12)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (170, 'NGANZAI', 12)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (171, 'SHANI', 12)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (172, 'AKPABUYO', 13)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (173, 'ODUKPANI', 13)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (174, 'AKAMKPA', 13)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (175, 'BIASE', 13)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (176, 'ABI', 13)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (177, 'IKOM', 13)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (178, 'YARKUR', 13)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (179, 'ODUBRA', 13)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (180, 'BOKI', 13)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (181, 'OGOJA', 13)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (182, 'YALA', 13)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (183, 'OBANLIKU', 13)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (184, 'OBUDU', 13)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (185, 'CALABAR SOUTH', 13)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (186, 'ETUNG', 13)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (187, 'BEKWARA', 13)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (188, 'BAKASSI', 13)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (189, 'CALABAR MUNICIPALITY', 13)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (190, 'OSHIMILI', 14)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (191, 'ANIOCHA', 14)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (192, 'ANIOCHA SOUTH', 14)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (193, 'IKA SOUTH', 14)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (194, 'IKA NORTH-EAST', 14)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (195, 'NDOKWA WEST', 14)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (196, 'NDOKWA EAST', 14)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (197, 'ISOKO SOUTH', 14)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (198, 'ISOKO NORTH', 14)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (199, 'BOMADI', 14)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (200, 'BURUTU', 14)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (201, 'UGHELLI SOUTH', 14)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (202, 'UGHELLI NORTH', 14)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (203, 'ETHIOPE WEST', 14)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (204, 'ETHIOPE EAST', 14)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (205, 'SAPELE', 14)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (206, 'OKPE', 14)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (207, 'WARRI NORTH', 14)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (208, 'WARRI SOUTH', 14)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (209, 'UVWIE', 14)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (210, 'UDU', 14)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (211, 'WARRI CENTRAL', 14)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (212, 'UKWANI', 14)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (213, 'OSHIMILLI NORTH', 14)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (214, 'PATANI', 14)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (215, 'AFIKPO SOUTH', 15)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (216, 'AFIKPO NORTH', 15)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (217, 'ONICHA', 15)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (218, 'OHAOZARA', 15)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (219, 'ABAKILIKI', 15)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (220, 'ISHIELU', 15)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (221, 'IKWO', 15)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (222, 'EZZA', 15)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (223, 'EZZA SOUTH', 15)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (224, 'OHAUKWU', 15)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (225, 'EBONYI', 15)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (226, 'IVO', 15)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (227, 'ESSAN NORTH-EAST', 16)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (228, 'ESAN CENTRAL', 16)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (229, 'ESAN WEST', 16)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (230, 'EGOR', 16)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (231, 'UKPOBA', 16)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (232, 'ETSAKO CENTRAL ', 16)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (233, 'IGUEBEN', 16)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (234, 'OREDO', 16)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (235, 'OVIA SOUTHWEST', 16)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (236, 'OVIA SOUTH-EAST', 16)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (237, 'ORHIONWON ', 16)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (238, 'UHUNMWONDE', 16)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (239, 'ETSAKO EAST', 16)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (240, 'ESAN SOUTH-EAST', 16)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (241, 'ADO', 17)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (242, 'EKITI-EAST', 17)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (243, 'EKITI-WEST', 17)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (244, 'EMURE-ISE-ORUN', 17)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (245, 'EKITI SOUTH-WEST', 17)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (246, 'IKARE', 17)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (247, 'IREPODUN', 17)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (248, 'IJERO', 17)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (249, 'IDO-OSI', 17)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (250, 'OYE', 17)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (251, 'IKOLE', 17)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (252, 'MOBA', 17)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (253, 'GBONYIN', 17)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (254, 'EFON', 17)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (255, 'ISE-ORUN', 17)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (256, 'ILEJEMEJE', 17)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (257, 'ENUGU SOUTH', 18)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (258, 'IGBO-EZE SOUTH ', 18)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (259, 'ENUGU NORTH', 18)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (260, 'NKANU', 18)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (261, 'UDI AGWU', 18)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (262, 'OJI-RIVER', 18)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (263, 'EZEAGU', 18)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (264, 'IGBO-EZE NORTH', 18)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (265, 'ISI-UZO', 18)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (266, 'NSUKKA', 18)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (267, 'IGBO-EKITI', 18)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (268, 'UZO-UWANI', 18)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (269, 'ENUGU EAST', 18)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (270, 'ANINRI', 18)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (271, 'NKANU EAST', 18)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (272, 'UDEDU', 18)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (273, 'AKKO', 19)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (274, 'BALANGA', 19)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (275, 'BILLIRI', 19)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (276, 'DUKKU', 19)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (277, 'KALTUNGO', 19)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (278, 'KWAMI', 19)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (279, 'SHOMGOM', 19)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (280, 'FUNAKAYE', 19)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (281, 'GOMBE', 19)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (282, 'NAFADA-BAJOGA', 19)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (283, 'YAMALTU-DELTA', 19)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (284, 'ABOH-MBAISE', 2)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (285, 'AHIAZU-MBAISE ', 2)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (286, 'EZINIHITTE', 2)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (287, 'IDEATO NORTH', 2)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (288, 'IDEATO SOUTH', 2)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (289, 'IHITTE-UBOMA', 2)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (290, 'IKEDURU', 2)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (291, 'ISIALA MBANO', 2)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (292, 'ISU', 2)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (293, 'MBAITOLI', 2)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (294, 'NGOR-OKPALA', 2)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (295, 'NJABA', 2)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (296, 'NWANGELE', 2)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (297, 'NKWERRE', 2)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (298, 'OBOWO', 2)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (299, 'OGUTA', 2)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (300, 'OHAJI-EGBEMA', 2)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (301, 'OKIGWE', 2)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (302, 'ORSU', 2)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (303, 'ORU EAST', 2)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (304, 'ORU WEST', 2)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (305, 'OWERRI NORTH', 2)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (306, 'OWERRI WEST', 2)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (307, 'AUYO', 20)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (308, 'BABURA', 20)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (309, 'BIRNI KUDU ', 20)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (310, 'BIRINIWA', 20)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (311, 'BUJI', 20)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (312, 'DUTSE', 20)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (313, 'GAGARAWA', 20)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (314, 'GARKI', 20)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (315, 'GUMEL', 20)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (316, 'GURI', 20)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (317, 'GWARAM', 20)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (318, 'GWIWA', 20)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (319, 'HADEJIA', 20)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (320, 'JAHUN', 20)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (321, 'KAFIN HAUSA ', 20)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (322, 'KAUGAMA KAZAURE', 20)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (323, 'KIRI KASAMMA', 20)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (324, 'KIYAWA', 20)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (325, 'MAIGATARI', 20)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (326, 'MALAM MADORI', 20)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (327, 'MIGA', 20)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (328, 'RINGIM', 20)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (329, 'RONI', 20)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (330, 'SULE-TANKARKAR', 20)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (331, 'TAURA', 20)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (332, 'YANKWASHI', 20)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (333, 'BIRNI-GWARI', 21)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (334, 'CHIKUM', 21)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (335, 'GIWA', 21)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (336, 'IGABI', 21)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (337, 'IKARA', 21)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (338, 'JABA', 21)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (339, 'JEMA''A', 21)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (340, 'KACHIA', 21)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (341, 'KADUNNA NORTH', 21)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (342, 'KADUNNA SOUTH', 21)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (343, 'KAGARKO', 21)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (344, 'KAJURU', 21)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (345, 'KAURA', 21)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (346, 'KAURU', 21)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (347, 'KUBAU', 21)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (348, 'KUDAN', 21)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (349, 'LERE', 21)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (350, 'MAKARFI', 21)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (351, 'SABON-GARI', 21)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (352, 'SANGA', 21)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (353, 'SOBA', 21)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (354, 'ZANGO-KATAF', 21)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (355, 'ZARIA', 21)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (356, 'AJINGI', 22)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (357, 'ALBASU', 22)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (358, 'BAGWAI', 22)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (359, 'BEBEJI', 22)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (360, 'BICHI', 22)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (361, 'BUNKURE', 22)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (362, 'DALA', 22)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (363, 'DAMBATTA', 22)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (364, 'DAWAKIN KUDU', 22)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (365, 'DAWAKIN TOFA', 22)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (366, 'DOGUWA ', 22)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (367, 'FAGGE', 22)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (368, 'GABASAWA', 22)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (369, 'GARKO', 22)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (370, 'GARUM', 22)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (371, 'MALLAM', 22)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (372, 'GAYA', 22)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (373, 'GEZAWA', 22)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (374, 'GWALE', 22)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (375, 'GWARZO', 22)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (376, 'KABO', 22)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (377, 'KANO MUNICIPAL', 22)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (378, 'KARAYE', 22)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (379, 'KIBIYA', 22)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (380, 'KIRU', 22)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (381, 'KUMBOTSO', 22)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (382, 'KUNCHI', 22)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (383, 'KURA', 22)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (384, 'MADOBI', 22)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (385, 'MAKODA', 22)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (386, 'MINJIBIR', 22)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (387, 'NASARAWA', 22)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (388, 'RANO', 22)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (389, 'RIMIN GADO', 22)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (390, 'ROGO', 22)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (391, 'SHANONO', 22)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (392, 'SUMAILA', 22)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (393, 'TAKALI', 22)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (394, 'TARAUNI', 22)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (395, 'TOFA', 22)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (396, 'TSANYAWA', 22)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (397, 'TUDUN WADA', 22)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (398, 'UNGOGO', 22)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (399, 'WARAWA', 22)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (400, 'WUDIL', 22)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (401, 'BAKORI', 23)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (402, 'BATAGARAWA', 23)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (403, 'BATSARI', 23)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (404, 'BAURE', 23)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (405, 'BINDAWA', 23)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (406, 'CHARANCHI', 23)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (407, 'DANDUME', 23)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (408, 'DANJA', 23)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (409, 'DAN MUSA', 23)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (410, 'DAURA', 23)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (411, 'DUTSI', 23)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (412, 'DUTSIN-MA', 23)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (413, 'FASKARI', 23)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (414, 'FUNTUA', 23)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (415, 'INGAWA', 23)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (416, 'JIBIA', 23)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (417, 'KAFUR', 23)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (418, 'KAITA', 23)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (419, 'KANKARA', 23)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (420, 'KANKIA', 23)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (421, 'KATSINA', 23)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (422, 'KURFI', 23)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (423, 'KUSADA', 23)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (424, 'MAI''ADUA', 23)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (425, 'MALUMFASHI', 23)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (426, 'MANI', 23)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (427, 'MASHI', 23)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (428, 'MATAZUU', 23)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (429, 'MUSAWA', 23)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (430, 'RIMI', 23)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (431, 'SABUWA', 23)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (432, 'SAFANA', 23)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (433, 'SANDAMU', 23)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (434, 'ZANGO', 23)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (435, 'ALEIRO', 24)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (436, 'AREWA-DANDI', 24)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (437, 'ARGUNGU', 24)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (438, 'AUGIE', 24)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (439, 'BAGUDO', 24)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (440, 'BIRNIN KEBBI', 24)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (441, 'BUNZA', 24)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (442, 'DANDI', 24)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (443, 'FAKAI', 24)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (444, 'GWANDU', 24)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (445, 'JEGA', 24)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (446, 'KALGO', 24)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (447, 'KOKO-BESSE', 24)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (448, 'MAIYAMA', 24)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (449, 'NGASKI', 24)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (450, 'SAKABA', 24)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (451, 'SHANGA', 24)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (452, 'SURU', 24)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (453, 'WASAGU-DANKO', 24)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (454, 'YAURI', 24)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (455, 'ZURU', 24)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (456, 'ADAVI', 25)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (457, 'AJAOKUTA', 25)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (458, 'ANKPA', 25)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (459, 'BASSA', 25)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (460, 'DEKINA', 25)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (461, 'IBAJI', 25)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (462, 'IDAH', 25)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (463, 'IGALAMELA-ODOLU', 25)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (464, 'IJUMU', 25)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (465, 'KABBA-BUNU', 25)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (466, 'KOGI', 25)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (467, 'LOKOJA', 25)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (468, 'MOPA-MURO', 25)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (469, 'OFU', 25)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (470, 'OGORI-MANGONGO', 25)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (471, 'OKEHI', 25)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (472, 'OKENE', 25)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (473, 'OLAMABOLO', 25)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (474, 'OMALA', 25)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (475, 'YAGBA EAST', 25)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (476, 'YAGBA WEST ', 25)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (477, 'ASA', 26)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (478, 'BARUTEN', 26)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (479, 'EDU', 26)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (480, 'EKITI', 26)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (481, 'IFELODUN', 26)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (482, 'ILORIN EAST', 26)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (483, 'ILORIN WEST', 26)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (484, 'IREPODUN', 26)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (485, 'ISIN', 26)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (486, 'KAIAMA', 26)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (487, 'MORO', 26)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (488, 'OFFA', 26)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (489, 'OKE-ERO', 26)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (490, 'OYUN', 26)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (491, 'PATEGI', 26)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (492, 'AGEGE', 27)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (493, 'AJEROMI-IFELODUN', 27)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (494, 'ALIMOSHO', 27)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (495, 'AMUWO-ODOFIN', 27)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (496, 'APAPA', 27)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (497, 'BADAGRY', 27)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (498, 'EPE', 27)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (499, 'ETI-OSA', 27)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (500, 'IBEJU-LEKKI', 27)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (501, 'IFAKO-IJAYE', 27)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (502, 'IKEJA', 27)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (503, 'IKORODU', 27)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (504, 'KOSOFE', 27)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (505, 'LAGOS ISLAND', 27)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (506, 'LAGOS MAINLAND ', 27)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (507, 'MUSHIN', 27)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (508, 'OJO', 27)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (509, 'OSHODI-ISOLO', 27)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (510, 'SHOMOLU', 27)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (511, 'SURULERE', 27)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (512, 'AKWANGA', 28)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (513, 'AWE', 28)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (514, 'DOMA', 28)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (515, 'KARU', 28)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (516, 'KEANA', 28)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (517, 'KEFFI', 28)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (518, 'KOKONA', 28)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (519, 'LAFIA', 28)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (520, 'NASARAWA', 28)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (521, 'NASARAWA-EGGON', 28)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (522, 'OBI', 28)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (523, 'TOTO', 28)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (524, 'WAMBA', 28)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (525, 'AGAIE', 29)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (526, 'AGWARA', 29)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (527, 'BIDA', 29)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (528, 'BORGU', 29)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (529, 'BOSSO', 29)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (530, 'CHANCHAGA', 29)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (531, 'EDATI', 29)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (532, 'GBAKO', 29)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (533, 'GURARA', 29)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (534, 'KATCHA', 29)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (535, 'KONTAGORA', 29)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (536, 'LAPAI', 29)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (537, 'LAVUN', 29)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (538, 'MAGAMA', 29)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (539, 'MARIGA', 29)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (540, 'MASHEGU', 29)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (541, 'MOKWA', 29)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (542, 'MUYA', 29)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (543, 'PAILORO', 29)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (544, 'RAFI', 29)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (545, 'RIJAU', 29)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (546, 'SHIRORO', 29)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (547, 'SULEJA', 29)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (548, 'TAFA', 29)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (549, 'WUSHISHI', 29)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (550, 'ABEOKUTA NORTH', 30)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (551, 'ABEOKUTA SOUTH', 30)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (552, 'ADO-ODO-OTA', 30)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (553, 'EGBADO NORTH', 30)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (554, 'EGBADO SOUTH', 30)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (555, 'EWEKORO', 30)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (556, 'IFO', 30)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (557, 'IJEBU EAST', 30)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (558, 'IJEBU NORTH', 30)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (559, 'IJEBU NORTH EAST', 30)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (560, 'IJEBU ODE ', 30)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (561, 'IKENNE', 30)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (562, 'IMEKO-AFON', 30)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (563, 'IPOKIA ', 30)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (564, 'OBAFEMI-OWODE', 30)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (565, 'OGUN WATERSIDE', 30)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (566, 'ODEDA', 30)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (567, 'ODOGBOLU', 30)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (568, 'REMO NORTH ', 30)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (569, 'SHAGAMU', 30)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (570, 'AKOKO NORTH EAST ', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (571, 'AKOKO NORTH WEST', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (572, 'AKOKO SOUTH AKURE EAST', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (573, 'AKOKO SOUTH WEST', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (574, 'AKURE NORTH ', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (575, 'AKURE SOUTH', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (576, 'ESE-ODO', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (577, 'IDANRE', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (578, 'IFEDORE', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (579, 'ILAJE', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (580, 'ILE-OLUJI', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (581, 'OKEIGBO', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (582, 'IRELE', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (583, 'ODIGBO', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (584, 'OKITIPUPA', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (585, 'ONDO EAST', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (586, 'ONDO WEST', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (587, 'OSE', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (588, 'OWO', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (589, 'AIYEDIRE ', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (590, 'ATAKUMOSA EAST', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (591, 'ATAKUMOSA WEST', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (592, 'BOLUWADURO', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (593, 'BORIPE', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (594, 'EDE NORTH', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (595, 'EDE SOUTH', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (596, 'EGBEDORE ', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (597, 'EJIGBO', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (598, 'IFE CENTRAL', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (599, 'IFE EAST', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (600, 'IFE NORTH ', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (601, 'IFE SOUTH', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (602, 'IFEDAYO', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (603, 'IFELODUN ', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (604, 'ILA', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (605, 'ILESHA EAST', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (606, 'ILESHA WEST', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (607, 'IREPODUN', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (608, 'IREWOLE ', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (609, 'ISOKAN', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (610, 'IWO', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (611, 'OBOKUN', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (612, 'ODO-OTIN', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (613, 'OLA-OLUWA', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (614, 'OLORUNDA', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (615, 'ORIADE', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (616, 'OROLU', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (617, 'OSOGBO', 31)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (618, 'AFIJIO', 33)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (619, 'AKINYELE', 33)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (620, 'ATIBA', 33)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (621, 'ATIGBO', 33)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (622, 'EGBEDA', 33)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (623, 'IBADAN CENTRAL', 33)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (624, 'IBADAN NORTH', 33)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (625, 'IBADAN NORTH WEST', 33)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (626, 'IBADAN SOUTH EAST', 33)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (627, 'IBADAN SOUTH WEST', 33)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (628, 'IBARAPA CENTRAL', 33)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (629, 'IBARAPA EAST', 33)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (630, 'IBARAPA NORTH', 33)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (631, 'IDO', 33)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (632, 'IREPO', 33)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (633, 'ISEYIN', 33)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (634, 'ITESIWAJU', 33)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (635, 'IWAJOWA', 33)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (636, 'KAJOLA', 33)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (637, 'LAGELU OGBOMOSHO NORTH ', 33)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (638, 'OGBOMOSHO SOUTH', 33)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (639, 'OGO OLUWA', 33)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (640, 'OLORUNSOGO', 33)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (641, 'OLUYOLE', 33)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (642, 'ONA-ARA', 33)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (643, 'ORELOPE', 33)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (644, 'ORI IRE', 33)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (645, 'OYO EAST', 33)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (646, 'OYO WEST', 33)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (647, 'SAKI EAST ', 33)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (648, 'SAKI WEST', 33)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (649, 'SURULERE', 33)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (650, 'BARIKIN LADI', 34)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (651, 'BASSA', 34)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (652, 'BOKKOS', 34)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (653, 'JOS EAST', 34)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (654, 'JOS NORTH', 34)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (655, 'JOS SOUTH', 34)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (656, 'KANAM', 34)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (657, 'KANKE', 34)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (658, 'LANGTANG NORTH', 34)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (659, 'LANGTANG SOUTH', 34)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (660, 'MANGU', 34)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (661, 'MIKANG', 34)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (662, 'PANKSHIN', 34)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (663, 'QUA''AN PAN', 34)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (664, 'RIYOM', 34)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (665, 'SHENDAM', 34)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (666, 'WASE', 34)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (667, 'ABUA-ODUAL', 35)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (668, 'AHOADA EAST', 35)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (669, 'AHOADA WEST', 35)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (670, 'AKUKU TORU', 35)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (671, 'ADONI', 35)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (672, 'ASARI-TORU', 35)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (673, 'BONNY', 35)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (674, 'DEGEMA', 35)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (675, 'EMOHUA', 35)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (676, 'ELEME', 35)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (677, 'ETCHE', 35)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (678, 'GOKANA', 35)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (679, 'IKWERRE', 35)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (680, 'KHANA', 35)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (681, 'OBIA-AKPOR', 35)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (682, 'OGBA-EGBEMA-NDONI', 35)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (683, 'OGU-BOLO', 35)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (684, 'OKIRIKA', 35)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (685, 'OMUMMA', 35)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (686, 'OPOBO-NKORO', 35)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (687, 'OYIGBO', 35)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (688, 'PORT-HARCOURT', 35)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (689, 'TAI', 35)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (690, 'BINJI', 36)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (691, 'BODINGA', 36)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (692, 'DANGE-SHNSI', 36)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (693, 'GADA', 36)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (694, 'GORONYO', 36)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (695, 'GUDU', 36)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (696, 'GAWABAWA', 36)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (697, 'ILLELA', 36)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (698, 'ISA', 36)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (699, 'KWARE', 36)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (700, 'KEBBE', 36)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (701, 'RABAH', 36)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (702, 'SABON BIRNI', 36)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (703, 'SHAGARI', 36)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (704, 'SILAME', 36)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (705, 'SOKOTO NORTH', 36)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (706, 'SOKOTO SOUTH', 36)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (707, 'TAMBUWAL', 36)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (708, 'TQNGAZA', 36)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (709, 'TURETA', 36)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (710, 'WAMAKO', 36)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (711, 'WURNO', 36)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (712, 'YABO', 36)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (713, 'ARDO-KOLA', 37)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (714, 'BALI', 37)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (715, 'DONGA', 37)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (716, 'GASHAKA', 37)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (717, 'GASHAKA', 37)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (718, 'CASSOL', 37)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (719, 'IBI', 37)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (720, 'JALINGO', 37)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (721, 'KARIN-LAMIDO', 37)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (722, 'KURMI', 37)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (723, 'LAU', 37)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (724, 'SARDAUNA', 37)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (725, 'TAKUM', 37)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (726, 'USSA', 37)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (727, 'WUKARI', 37)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (728, 'YORRO', 37)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (729, 'ZING', 37)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (730, 'BADE', 38)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (731, 'BURSARI', 38)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (732, 'DAMATURU', 38)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (733, 'FIKA', 38)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (734, 'FUNE', 38)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (735, 'GEIDAM', 38)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (736, 'GUJBA', 38)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (737, 'GULANI', 38)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (738, 'JAKUSO', 38)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (739, 'KARASUWA', 38)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (740, 'KARAWA', 38)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (741, 'MACHINA', 38)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (742, 'NANGERE', 38)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (743, 'NGURU POTISKUM', 38)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (744, 'TARMUA', 38)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (745, 'YUNUSARI', 38)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (746, 'YUSUFARI', 38)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (747, 'ANKA', 39)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (748, 'BAKURA', 39)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (749, 'BIRININ MAGAJI', 39)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (750, 'BUKKUYUM', 39)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (751, 'BUNGUDU', 39)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (752, 'GUMMI', 39)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (753, 'GUSAU', 39)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (754, 'KAURA', 39)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (755, 'NAMODA', 39)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (756, 'MARADUN', 39)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (757, 'MARU', 39)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (758, 'SHINKAFI', 39)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (759, 'TALATA MAFARA', 39)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (760, 'TSAFE', 39)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (761, 'ZURMI', 39)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (762, 'GWAGWALADA', 40)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (763, 'KUJE', 40)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (764, 'ABAJI', 40)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (765, 'ABUJA MUNICIPAL', 40)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (766, 'BWARI', 40)");
            Sql("INSERT INTO LocalGovs (Id, LGAName, StatesId) VALUES (767, 'KWALI', 40)");
            Sql("SET IDENTITY_INSERT LocalGovs OFF");

        }

        public override void Down()
        {
        }
    }
}
