// <auto-generated />
namespace SchoolPortal.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class resultarchivesupdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(resultarchivesupdate));
        
        string IMigrationMetadata.Id
        {
            get { return "202004291036351_resultarchivesupdate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
