// <auto-generated />
namespace SchoolPortal.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Archiveaveragescore : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Archiveaveragescore));
        
        string IMigrationMetadata.Id
        {
            get { return "202005011004363_Archiveaveragescore"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
