// <auto-generated />
namespace SchoolPortal.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class finance2049 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(finance2049));
        
        string IMigrationMetadata.Id
        {
            get { return "202109021844203_finance2049"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
