// <auto-generated />
namespace SchoolPortal.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class classsubjectsetting : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(classsubjectsetting));
        
        string IMigrationMetadata.Id
        {
            get { return "202103081343148_classsubjectsetting"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
